#!/usr/bin/env node
/**
 * Symbol library generator — Project Theos.
 *
 * Extracts a curated set of religious symbols from Font Awesome Free (solid)
 * into a small self-hosted data file (src/data/symbols.ts). We ship only the
 * path data — there is no Font Awesome runtime dependency in the built site.
 *
 * Icons: Font Awesome Free, CC BY 4.0 — https://fontawesome.com
 * Run:   npm run gen:symbols   (only needed when adding/updating symbols)
 */
import * as fa from '@fortawesome/free-solid-svg-icons';
import { writeFileSync, mkdirSync } from 'node:fs';

// key (tradition-agnostic, reusable) → Font Awesome export → human label.
// Many more than we use today, so future traditions are a one-line change.
const WANT = [
  ['cross', 'faCross', 'Cross (Christianity)'],
  ['star-and-crescent', 'faStarAndCrescent', 'Star and crescent (Islam)'],
  ['om', 'faOm', 'Om (Hinduism)'],
  ['dharmachakra', 'faDharmachakra', 'Dharmachakra (Buddhism)'],
  ['star-of-david', 'faStarOfDavid', 'Star of David (Judaism)'],
  ['khanda', 'faKhanda', 'Khanda (Sikhism)'],
  ['yin-yang', 'faYinYang', 'Yin and yang (Taoism)'],
  ['menorah', 'faMenorah', 'Menorah (Judaism)'],
  ['bahai', 'faBahai', 'Nine-pointed star (Baháʼí)'],
  ['ankh', 'faAnkh', 'Ankh'],
  ['hamsa', 'faHamsa', 'Hamsa'],
  ['peace', 'faPeace', 'Peace'],
  ['gopuram', 'faGopuram', 'Gopuram (temple)'],
  ['torii-gate', 'faToriiGate', 'Torii gate (Shinto)'],
  ['kaaba', 'faKaaba', 'Kaaba'],
  ['vihara', 'faVihara', 'Vihara'],
  ['atom', 'faAtom', 'Atom (secular)'],

  // Section markers — one per fixed template slot (see src/data/sections.ts).
  // Tradition-agnostic on purpose, so tradition #4+ inherits them for free.
  ['seedling', 'faSeedling', 'Seedling (Origins & Cosmology)'],
  ['heart', 'faHeart', 'Heart (Core Beliefs)'],
  ['sun', 'faSun', 'Sun (A Day / A Life)'],
  ['hands-praying', 'faHandsPraying', 'Praying hands (Practice & Ritual)'],
  ['book-open', 'faBookOpen', 'Open book (Sacred Text & Voice)'],
  ['shapes', 'faShapes', 'Shapes (Symbols & Sensory World)'],
  ['scale-balanced', 'faScaleBalanced', 'Balanced scale (Tensions & Questions)'],
];

const out = {};
const missing = [];
for (const [key, exp, label] of WANT) {
  const def = fa[exp];
  if (!def?.icon) {
    missing.push(exp);
    continue;
  }
  const [w, h, , , path] = def.icon;
  if (typeof path !== 'string') {
    missing.push(exp + ' (non-string path)');
    continue;
  }
  out[key] = { viewBox: `0 0 ${w} ${h}`, path, label };
}

const banner =
  `// AUTO-GENERATED by scripts/gen-symbols.mjs — do not edit by hand.\n` +
  `// Icons: Font Awesome Free (solid), CC BY 4.0 — https://fontawesome.com\n` +
  `// Regenerate with: npm run gen:symbols\n`;

const body =
  `export interface Glyph {\n` +
  `  viewBox: string;\n` +
  `  path: string;\n` +
  `  label: string;\n` +
  `}\n\n` +
  `export const SYMBOLS = ${JSON.stringify(out, null, 2)} as const satisfies Record<string, Glyph>;\n\n` +
  `export type SymbolName = keyof typeof SYMBOLS;\n`;

mkdirSync(new URL('../src/data/', import.meta.url), { recursive: true });
writeFileSync(new URL('../src/data/symbols.ts', import.meta.url), banner + '\n' + body);

console.log(`Wrote ${Object.keys(out).length} symbols → src/data/symbols.ts`);
if (missing.length) console.warn(`Skipped (not in free set): ${missing.join(', ')}`);
